version: "3.9"

services:
  rest-recipe-api:
    container_name: rest-recipe-api
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py 0.0.0.0:8000"
